package query_consts

const (
	INSERT_INTO_TBL_VALUES_VAL        = " INSERT INTO %s VALUES %s ON CONFLICT DO NOTHING"
	SELECT_COL_FROM_TBL_WHERE_CND     = " SELECT %s FROM %s WHERE %s"
	SELECT_COL_FROM_TBL               = " SELECT %s FROM %s"
	UPDATE_TBL_SET_VAL_WHERE_CND      = " UPDATE %s SET %s WHERE %s"
	DELETE_FROM_TBL_WHERE_CND         = " DELETE FROM %s WHERE %s"
	DELETE_CASCADE_FROM_TBL_WHERE_CND = " DELETE CASCADE FROM %s WHERE %s"

	SELECT_COL1_FROM_TBL1_WHERE_CND1_SELECT_COL2_FROM_TBL2_CND2 = ` 
	SELECT %s FROM %s
	WHERE %s=(` + SELECT_COL_FROM_TBL_WHERE_CND + `)
	`

	ON_CONFLICT_DO_NOTHING = " ON CONFLICT DO NOTHING"
	ORDER_BY_COL           = " ORDER BY %s"

	// INSERT_INTO_TBL1_SELECT_COL_FROM_TBL2_WHERE_CND = `
	// INSERT INTO %s
	// SELECT %s FROM %s WHERE %s
	// ON CONFLICT DO NOTHING;
	// `

	// DELETE_FROM_TBL1_WHERE_CND1_IN_SELECT_COL_FROM_COL2_FROM_TBL2_WHERE_CND2 = `
	// DELETE FROM %s
	// WHERE %s IN (` + SELECT_COL_FROM_TBL_WHERE_CND + `);
	// `

)
