package query_consts

const (
	INSERT_INTO_TBL_VALUES_VAL_RETURNING_RET = "INSERT INTO %s VALUES %s RETURNING %s"
	INSERT_INTO_TBL_VALUES_VAL               = "INSERT INTO %s VALUES %s"
	SELECT_COL_FROM_TBL_WHERE_CND            = "SELECT %s FROM %s WHERE %s"
	SELECT_COL_FROM_TBL                      = "SELECT %s FROM %s"
	UPDATE_TBL_SET_VAL_WHERE_CND             = "UPDATE %s SET %s WHERE %s"
	DELETE_FROM_TBL_WHERE_CND                = "DELETE FROM %s WHERE %s"
	DELETE_CASCADE_FROM_TBL_WHERE_CND        = "DELETE CASCADE FROM %s WHERE %s"
)
